version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
networks:
  frontend:
  backend:
